import {bounds,issues} from './layout.js';
import {hangingStatus,wallFasteners} from './hanging.js';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function svgShape(p,attrs){
  if(p.shape==='circle'||p.shape==='oval')return `<ellipse cx="${p.w/2}" cy="${p.h/2}" rx="${p.w/2}" ry="${p.h/2}" ${attrs}/>`;
  if(p.shape==='hexagon')return `<polygon points="${p.w*.25},0 ${p.w*.75},0 ${p.w},${p.h*.5} ${p.w*.75},${p.h} ${p.w*.25},${p.h} 0,${p.h*.5}" ${attrs}/>`;
  if(p.shape==='arch')return `<path d="M0 ${p.h}V${p.h/2}A${p.w/2} ${p.h/2} 0 0 1 ${p.w} ${p.h/2}V${p.h}Z" ${attrs}/>`;
  return `<rect width="${p.w}" height="${p.h}" ${attrs}/>`;
}
export function hangingMap(s,nails=false){
  const size=Math.max(s.wall.w,s.wall.h),stroke=size/700,font=size/70,r=size/210,pad=size/22,caption=Math.min(size/85,s.wall.w/90),confirmed=s.items.filter(p=>hangingStatus(p).ready).length;
  const shapes=s.items.map((p,i)=>{
    const odd=p.rotation%180!==0,base={...p,w:odd?p.h:p.w,h:odd?p.w:p.h};
    return `<g transform="translate(${p.x+p.w/2} ${p.y+p.h/2}) rotate(${p.rotation}) translate(${-base.w/2} ${-base.h/2})">${svgShape(base,`fill="${nails?'#f7f7f1':'#ebeade'}" stroke="${nails?'#aab7ab':p.color}" stroke-width="${stroke}"`)}</g><text x="${p.x+p.w/2}" y="${p.y+p.h/2}" text-anchor="middle" dominant-baseline="middle" font-size="${font}" fill="#576e5c">${i+1}</text>`;
  }).join('');
  const marks=nails?s.items.flatMap((p,i)=>wallFasteners(p,s.wall).filter(q=>!q.outside).map(q=>`<g fill="none" stroke="#b1482e" stroke-width="${stroke}"><circle cx="${q.x}" cy="${q.y}" r="${r}"/><path d="M${q.x-r*1.7} ${q.y}h${r*3.4}M${q.x} ${q.y-r*1.7}v${r*3.4}"/></g><text x="${q.x+r*2}" y="${q.y-r*1.7}" font-size="${font*.8}" fill="#973720" stroke="#fff" stroke-width="${stroke*2}" paint-order="stroke">${i+1}${q.label}</text>`)).join(''):'';
  return `<svg class="guide-diagram" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="${nails?'Measured nail positions, viewed facing the wall':'Numbered frame placement plan'}" viewBox="${-pad} ${-pad} ${s.wall.w+pad*2} ${s.wall.h+pad*2}" font-family="Arial,sans-serif"><title>${nails?'Wallstory nail map':'Wallstory frame plan'}</title><desc>Facing the wall. Top and left refer to the measured wall rectangle. Only confirmed nail positions inside the wall are drawn. Use the guide tables for measurements.</desc><rect x="${-pad}" y="${-pad}" width="${s.wall.w+pad*2}" height="${s.wall.h+pad*2}" fill="#fff"/><rect width="${s.wall.w}" height="${s.wall.h}" fill="#fffdf5" stroke="#849c87" stroke-width="${stroke}"/>${shapes}${marks}<text x="0" y="${-pad*.4}" font-size="${caption}" fill="#526953">WALL TOP · Facing the wall</text><text x="0" y="${s.wall.h+pad*.65}" font-size="${caption}" fill="#526953">${nails?`${confirmed}/${s.items.length} frames confirmed · Crosshair = nail / screw`:'Numbers match your pieces'} · Not a full-size template</text></svg>`;
}
export function buildHangingGuide(s,interactive=true){
  const measure=n=>`${Number((n*(s.unit==='cm'?2.54:1)).toFixed(4))} ${s.unit}`;
  const v=issues(s),b=bounds(s.items),warn=v.outside.length||v.overlap.length||v.spacing.length||v.margin.length;
  const ready=s.items.filter(p=>hangingStatus(p).ready).length;
  const edits=(p,status)=>`<div class="guide-point-status"><p><strong>${esc(p.name)}</strong><br>${status}</p>${interactive?`<button class="outlined guide-edit-hangers" data-guide-hanging="${esc(p.id)}">Set hanging points</button>`:''}</div>`;
  return `${warn?'<p class="guide-warning">This plan has a fit or spacing warning. Review the wall before using these measurements.</p>':''}<div class="guide-summary"><span><strong>Wall</strong> ${measure(s.wall.w)} × ${measure(s.wall.h)}</span><span><strong>Gallery</strong> ${measure(b.w)} × ${measure(b.h)}</span><span><strong>Hanging measurements</strong> ${ready} of ${s.items.length} frames confirmed</span></div><p>All wall coordinates are measured while facing the wall. Start from the top and sides of the wall rectangle you entered. Verify dimensions with a tape measure.</p><h3 class="guide-section-title">1. Position the frames</h3><p>These distances locate the outside frame edges, including the frame itself.</p>${hangingMap(s)}<div class="guide-table-wrap"><table class="guide-table"><thead><tr><th>Piece</th><th>Outside size</th><th>Left edge<br>from wall left</th><th>Top edge<br>from wall top</th><th>Right edge<br>from wall right</th><th>Center<br>from wall left / top</th></tr></thead><tbody>${s.items.map((p,i)=>`<tr><td><strong>${i+1}. ${esc(p.name)}</strong></td><td>${measure(p.w)} × ${measure(p.h)}</td><td>${measure(p.x)}</td><td>${measure(p.y)}</td><td>${measure(s.wall.w-p.x-p.w)}</td><td>${measure(p.x+p.w/2)} / ${measure(p.y+p.h/2)}</td></tr>`).join('')}</tbody></table></div><h3 class="guide-section-title">2. Mark the nails / anchors</h3><p>Each crosshair marks a nail or screw, with the frame number and hanging-point letter. Back-view measurements are mirrored automatically. For wall hooks, the measured vertical hook offset is included.</p>${hangingMap(s,true)}${s.items.map((p,i)=>{
    const status=hangingStatus(p);if(!status.ready)return edits(p,esc(status.label)+' — nail coordinates withheld.');
    const fasteners=wallFasteners(p,s.wall);
    return `<section class="guide-nail-card"><h3>${i+1}. ${esc(p.name)} · Nail / anchor locations</h3>${fasteners.some(q=>q.outside)?'<p class="guide-warning">A fixing is outside the measured wall. Reposition this frame or check its hanging measurements before making holes.</p>':''}<div class="guide-table-wrap"><table class="guide-table"><thead><tr><th>Point</th><th>From wall left</th><th>From wall top</th><th>From wall right</th><th>From wall bottom</th></tr></thead><tbody>${fasteners.map(q=>`<tr><td><strong>${i+1}${q.label}</strong>${q.outside?' · OUTSIDE WALL':''}</td><td>${measure(q.x)}</td><td>${measure(q.y)}</td><td>${measure(q.right)}</td><td>${measure(q.bottom)}</td></tr>`).join('')}</tbody></table></div>${fasteners.map((q,j)=>{const point=p.hanging.points[j];return `<p><strong>${i+1}${q.label} support, looking at the back:</strong> ${measure(point.x)} from back left · ${measure(p.w-point.x)} from back right · ${measure(point.y)} below frame top. ${q.kind==='hook'?`Nail entry is ${measure(q.rise)} above this support point.`:'Direct nail / screw support.'}</p>`}).join('')}${interactive?`<button class="text-button guide-edit-hangers" data-guide-hanging="${esc(p.id)}">Edit hanging points</button>`:''}</section>`;
  }).join('')}<p class="muted"><strong>Before making holes:</strong> Mark the outlines with painter’s tape, confirm every support point against the actual hardware, and check the final wall positions. Wire must be measured under tension. The bottom reference is your wall rectangle’s bottom, which may differ from the floor. Screen previews and this diagram are not full-size templates.</p><p class="field-note">All coordinates use your entered measurements; the photo does not determine nail locations. Curved shapes use outside bounding rectangles for spacing checks.</p>`;
}
